"""Chakravyuh demo server — Gradio UI + replay curator."""

from server.episode_curator import (
    AGENT_COLORS,
    CURATED_EPISODES,
    AgentState,
    AnalyzerSnapshot,
    BankSnapshot,
    CuratedEpisode,
    ReplayedEpisode,
    compute_agent_states,
    format_agent_cards_html,
    format_attack_timeline_html,
    format_bank_panel,
    format_chat_html,
    format_suspicion_timeline,
    max_turn,
    outcome_badge,
    replay,
    replay_all,
    suspicion_score_for_turn,
)

__all__ = [
    "AGENT_COLORS",
    "AgentState",
    "AnalyzerSnapshot",
    "BankSnapshot",
    "CURATED_EPISODES",
    "CuratedEpisode",
    "ReplayedEpisode",
    "compute_agent_states",
    "format_agent_cards_html",
    "format_attack_timeline_html",
    "format_bank_panel",
    "format_chat_html",
    "format_suspicion_timeline",
    "max_turn",
    "outcome_badge",
    "replay",
    "replay_all",
    "suspicion_score_for_turn",
]
